name: okk
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "TITAN.utils"
          replace: "..utils"
      - name: Pull All Updates
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'there was a conflict'
          commit_options: '--no-verify'
          repository: .
          commit_user_name: kartikrajofficial
          commit_user_email: kartikphysics100.100@gmail.com
          commit_author: kartikrajofficial <kartikphysics100.100@gmail.com>
